package com._s.api.domain.order;

public enum OrderStatus {
    REALIZADO,
    AGUARDANDO_ASSINATURA_CLIENTE,
    ASSINADO,
    AGUARDANDO_PAGAMENTO,
    PAGAMENTO_APROVADO,
    AGUARDANDO_ENTREGA,
    ENTREGUE,
    CONCLUIDO
}
