spring.application.name=api

spring.datasource.url=jdbc:postgresql://ep-snowy-pine-ah897i4e-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lLHjiKPZS3E2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

api.security.token.secret=${JWT_SECRET:a278140c8502f3e3ee25f9941bfb103e}
api.security.token.issuer=${ISSUER:Meiflow-api-dev}
api.web.config.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}

logging.level.org.springframework.security=DEBUG

